## 선형회귀 (Linear Regression)

In [1]:
import numpy as np
# x = [1,2,3,4,5,6,7,8,9,10]
# arange()
X = np.arange(10).reshape(-1,1)
y = 2*X + 1 # >> x가 2차원이라서 / y는 브로드캐스팅 연산이 되니까 2차원으로 만들지 않아도됨

# print(X,y)
# print(X.shape, y.shape)


In [5]:
# train_test_split 함수로 데이터를 분할
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)
print(X_train)
print()
print(y_train)


(9, 2) (1, 2)
(9, 1) (1, 1)
[[1 1]
 [5 5]
 [0 0]
 [7 7]
 [2 2]
 [9 9]
 [4 4]
 [3 3]
 [6 6]]

[[ 6]
 [26]
 [ 1]
 [36]
 [11]
 [46]
 [21]
 [16]
 [31]]


In [15]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# scikit-learn의 선형회귀 모델
# 1. 모델 생성
model = LinearRegression()

# 2. 모델 학습
model.fit(X_train, y_train)

# 3. 모델 예측
y_pred = model.predict([[10,10]])
print(y_pred)

# 4. MSE 모델 평가
# mse = mean_squared_error(y_test, y_pred)
# print(mse)

print(model.coef_) #w1,w2
print(model.intercept_) #b

[[51.]]
[[2.5 2.5]]
[1.]


In [7]:
# Multi-Variale Linear Regression
# 변수가 2개 일때, x1, x2
# y = w1 * x1 + w2 * x2 + b


X1 = np.arange(10).reshape(-1, 1)
X2 = np.arange(10).reshape(-1, 1)

# X1과 X2를 합쳐서 튜플 X로 만듬
X = np.concatenate((X1, X2), axis=1)
print(X)

# 실제 모델이 튜닝해야할 대상, w1 =2 , w2 = 3, b = 1
# y 값을 생성하기 위한 수식
y = 2 * X1 + 3 * X2 + 1

# print(X1)
# print()
# print(X2)
# print()
# print(y)


[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]


In [8]:
# 데이터 분할

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)
print(X_train.shape, X_test.shape)


(9, 2) (1, 2)


In [ ]:
# 위의 X1, X2, y의 데이터 시각화
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(X1, X2, y)
ax.set_xlabel('X1')
ax.set_ylabel('X2')
ax.set_zlabel('y')
plt.show()
